linux-release:
  tags:
    - disco
  script:
    - ccache -z
    - export PATH=/usr/lib/ccache:$PATH
    - export CXX=g++-9
    - export CC=gcc-9
    - export BOOST_ROOT=~/boost_1_71_0
    - git submodule update --init --recursive
    - mkdir -p build
    - cd build
    - CXXFLAGS="-static" cmake -GNinja -DCMAKE_BUILD_TYPE=MinSizeRel ..
    - ninja pkg pkg-test
    - ./pkg-test
    - ccache -s
  artifacts:
    paths:
      - build/pkg

windows-release:
  tags:
    - windows
  script:
    - git submodule update --init --recursive
    - set WD=%cd%
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
    - cd %WD%
    - set BOOST_ROOT=C:\boost_1_70_0
    - mkdir build
    - cd build
    - cmake -GNinja -DCMAKE_BUILD_TYPE=MinSizeRel ..
    - ninja pkg pkg-test
    - pkg-test
  artifacts:
    paths:
      - build/pkg.exe
