linux-release:
  tags:
    - bionic
  script:
    - export BOOST_ROOT=/opt/boost_1_67_0-gcc-7
    - /bin/bash bootstrap.sh
    - mkdir -p build-release
    - cd build-release
    - cmake -GNinja -DCMAKE_BUILD_TYPE=MinSizeRel ..
    - ninja pkg pkg-test
    - ./pkg-test
  artifacts:
    paths:
      - build/pkg

windows-release:
  tags:
    - windows
  script:
    - set WD=%cd%
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
    - cd %WD%
    - set BOOST_ROOT=C:\boost_1_67_0
    - call bootstrap.bat
    - mkdir build-msvc-release
    - cd build-msvc-release
    - cmake -GNinja -DCMAKE_BUILD_TYPE=MinSizeRel ..
    - ninja pkg pkg-test
    - pkg-test
  artifacts:
    paths:
      - build/pkg.exe
